management:
  endpoint:
    health:
      show-details: never

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: WARN
    br.com.fiap.ecotrack: INFO
