CREATE TABLE registro_emissao (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa            VARCHAR(120)             NOT NULL,
    escopo             VARCHAR(20)              NOT NULL,
    fonte              VARCHAR(120)             NOT NULL,
    quantidade_co2e_kg NUMERIC(15, 3)           NOT NULL CHECK (quantidade_co2e_kg > 0),
    data_referencia    DATE                     NOT NULL,
    criado_em          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_registro_emissao_escopo CHECK (escopo IN ('ESCOPO_1', 'ESCOPO_2', 'ESCOPO_3'))
);

CREATE INDEX idx_registro_emissao_empresa ON registro_emissao (empresa);
CREATE INDEX idx_registro_emissao_escopo ON registro_emissao (escopo);
